Fatima Torre Hütt:
    icon: bridesmaid_fach.jpg
    fb: http://www.facebook.com/fatima.torrehutt?fref=ts
    desc: Hermana y mejor amiga de Maria, inseparables, siempre apoyando en las buenas y en las malas y persona favorita de Maria.
    title: Con mi Peach!!! Te amo neni!!
    slider: slider/fachis_maria.jpg

Elias Campos Andrade:
    icon: groomsmen_ely.jpg
    fb: http://www.facebook.com/elias.c.andrade.94?fref=ts
    desc: Primo y hermano de Alonso. El amor más grande que se le puede tener a un amigo, primo y hermano!
    title: Amaneciendo después de un gran festejo.
    slider: slider/eli_y_yo_slider.jpg

Mariana Castañeda Andrade:
    icon: bridesmaid_mariana.jpg
    fb: http://www.facebook.com/mariana.castaneda.790?fref=ts
    desc: La hermana y mejor amiga de Alonso, increíble mujer llena de fuerza y carácter.
    title: Muy orgulloso de mi hermanita. La mejor diseñadora del mundo!
    slider: slider/mariana_y_yo_graduacion.jpg

Julian Torre Hütt:
    icon: groomsmen_julis.jpg
    fb: http://www.facebook.com/julian.torrehutt?fref=ts
    desc: Hermano y mejor amigo de Maria, siempre atento para escuchar y apoyarte.
    title: Te quiero bro!
    slider: slider/julian_maria.jpg

Andrea Castañeda Andrade:
    icon: bridesmaid_bander.jpg
    fb: http://www.facebook.com/andreea.castaneda
    desc: La hermanita menor de Alonso. Personita favorita de Alonso, siempre alegre, positiva y auténtica.
    title: Festejando a la quinceañera más hermosa del mundo en Disney
    slider: slider/bander_disney.jpg

Lalo Ramirez Correa:
    icon: groomsmen_lalo.jpg
    fb: http://www.facebook.com/lalo.r.correa?fref=ts
    desc: Querido amigo de Alonso. Una persona integra y amigable.
    title: Coachella 2009
    slider: slider/lalo_coachella.jpg

Suzel Torre Hütt:
    icon: bridesmaid_chu.jpg
    fb: http://www.facebook.com/suzel.hutt?fref=ts
    desc: Hermana y persona muy especial para Maria, confiable y un gran apoyo para la familia.
    title: Chu y yo muy divertidas!!
    slider: slider/suzel_maria.jpg

Raúl Torres Fuentvilla:
    icon: groomsmen_raul.jpg
    fb: http://www.facebook.com/raul.fuentevilla?fref=ts
    desc: Mi chaparrito de oro. Amigo de Alonso desde la secundaria. Siempre buen amigo en la buenas y las malas.
    title: Lollapalooza 2010
    slider: slider/raul_y_yo.jpg

Andrea Torre Hütt:
    icon: bridesmaid_andrea.jpg
    fb: http://www.facebook.com/andrea.t.hutt?fref=ts
    desc: Hermana y gran persona, fiel y siempre al pendiente de todos.
    title: Andrea y yo muy contentas festejando a Fachis!
    slider: slider/andrea_maria.jpg

Jorge Puente Dominguez:
    icon: groomsmen_ponti.jpg
    fb: http://www.facebook.com/jorge.ponti.7?fref=ts
    desc: Querido amigo de Alonso y María. Siempre atento y responsable.
    title: Festejando mi cumple!
    slider: slider/ponti_en_cumple.jpg

Paola Torre Hütt:
    icon: bridesmaid_paola.jpg
    fb: http://www.facebook.com/paola.torre.16
    desc: Hermana mayor de Maria, la más noble, siempre alegrándote el día. Gran apoyo.
    title: Día de relajación y manicure, las amo!
    slider: slider/paola_maria.jpg

Mariano Torre Hütt:
    icon: groomsmen_mariano.jpg
    fb: http://www.facebook.com/torrehutt?fref=ts
    desc: Hermano de Maria, muy simpático, sociable y noble.
    title: Brothers and sisters, lov u!
    slider: slider/mariano_maria.jpg

Lucia Torre Hütt:
    icon: bridesmaid_lu.jpg
    fb: http://www.facebook.com/lucia.torre.5264?fref=ts
    desc: Hermana y gran amiga de Maria, siempre apoyando incondicionalmente.
    title: Felices todas!
    slider: slider/hermanas_lucia.jpg

Jorge Arellano Funes:
    icon: groomsmen_gio.jpg
    fb: http://www.facebook.com/JorgeFunes06?fref=ts
    desc: El amigo más antiguo de Alonso. Una persona en la que siempre se puede confiar!
    title: Te quiero amigo!
    slider: slider/giorgie_y_yo.jpg

Cristina Campos Andrade:
    icon: bridesmaid_cris.jpg
    fb: http://www.facebook.com/cristina.c.andrade.3?fref=ts
    desc: La prima hermana de Alonso. Crecieron juntos desde chicos y al igual que su hermano, Elias, siempre ha sido una persona muy especial para el.
    title: Festejando mi cumple muy contento con mi primita linda.
    slider: slider/festejando_con_cris.jpg

Carlos Hernandez Robles:
    icon: groomsmen_carlos.jpg
    fb: http://www.facebook.com/carlos.hernandez.3532507?fref=ts
    desc: Querido amigo de Alonso. Siempre presente, incluso a miles de kilómetros de distancia.
    title: Festejanodo mi graduación
    slider: slider/carlos_graduacion.jpg

Ximena Choriego Hütt:
    icon: bridesmaid_xime.jpg
    fb: http://www.facebook.com/ximena.choriegohutt
    desc: Prima hermana de Maria, persona muy especial confiable y noble, grandes amigas a pesar de la distancia.
    title: Bailando felices con las primas!
    slider: slider/xime_maria.jpg

Abraham Ponciano:
    icon: groomsmen_abry.jpg
    fb: http://www.facebook.com/Abryx?fref=ts
    desc: Amigo incondicional, lleno de vida y siempre presente cuando se le necesita.
    title: Que buen viaje! Gracias hermano!
    slider: slider/abry_barc.jpg
